["Res: fixed"]
color = "cccccc"
name = "Res: fixed"
description = "This has been fixed/done."

["Res: invalid"]
color = "cccccc"
name = "Res: invalid"
description = "This doesn't seem right. Reasons: Duplicate, cannot reproduced, incomoplete, ..."

["Res: wontfix"]
color = "cccccc"
name = "Res: wontfix"
description = "This will not be worked on"

["Sev: blocker"]
color = "ff6663"
name = "Sev: blocker"
description = "Blocks development and/or testing work, production could not run."

["Sev: major"]
color = "feb144"
name = "Sev: major"
description = "Major loss of function."

["Sev: minor"]
color = "fdfd97"
name = "Sev: minor"
description = "Minor loss of function, or other problem where easy workaround is present."

["Sev: none"]
color = "9ee07e"
name = "Sev: none"
description = "Nice to have, no urgence, for the times when there is time"

["Top: IBM-Ticket"]
color = "bfd4f2"
name = "Top: IBM-Ticket"
description = "A corresponding support ticket at IBM has been opened for this issue."

["Top: arc-ce"]
color = "b7c68b"
name = "Top: arc-ce"
description = "Tickets related to the Nordugrid ARC Compute Element instance"

["Top: documentation"]
color = "f4f0cb"
name = "Top: documentation"
description = "Improvements or additions to documentations"

["Top: hardware"]
color = "a29574"
name = "Top: hardware"
description = "Hardware related issue that lead to dirty fingers in the serverroom"

["Top: monitoring"]
color = "a29574"
name = "Top: monitoring"
description = "Monitoring the HPC machine(s), its appliances and users"

["Top: openmp"]
color = "b3a580"
name = "Top: openmp"
description = "OpenMP related issues"

["Top: puppet"]
color = "ded29e"
name = "Top: puppet"
description = "Issues touching puppet code"

["Top: researchstorage"]
color = "b7c68b"
name = "Top: researchstorage"
description = "Issue is related to the research storage and the underlying ESS"

["Top: slurm"]
color = "f4f0cb"
name = "Top: slurm"
description = "Slurm local researouce management server related issues"

["Typ: bug"]
color = "953830"
name = "Typ: bug"
description = "Something isn't working. Something needs a fix."

["Typ: enhancement"]
color = "506c33"
name = "Typ: enhancement"
description = "New functionality is needed. Something existing needs an enhancement."

["Typ: task"]
color = "35547a"
name = "Typ: task"
description = "Just a single task. Something needs to be done."
